-- =============================================================================
-- YMO Booking — seed data
-- Run AFTER schema.sql
-- =============================================================================

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Vehicle makes (sourced from yourmechaniconline.com)
-- ---------------------------------------------------------------------------
INSERT INTO `vehicle_makes` (`name`, `sort_order`) VALUES
    ('Maruti Suzuki',  10),
    ('Hyundai',        20),
    ('Honda',          30),
    ('Tata',           40),
    ('Mahindra',       50),
    ('Toyota',         60),
    ('Ford',           70),
    ('Volkswagen',     80),
    ('Skoda',          90),
    ('Renault',       100),
    ('Nissan',        110),
    ('Mitsubishi',    120),
    ('MG',            130),
    ('Jeep',          140),
    ('Volvo',         150),
    ('BMW',           160),
    ('Mercedes-Benz', 170),
    ('Audi',          180),
    ('Land Rover',    190),
    ('Lexus',         200),
    ('Jaguar',        210),
    ('Other',         999)
ON DUPLICATE KEY UPDATE `sort_order` = VALUES(`sort_order`);

-- ---------------------------------------------------------------------------
-- Default service packages (3 starter packages — admin can edit/extend)
-- ---------------------------------------------------------------------------
INSERT INTO `service_packages` (`id`, `name`, `slug`, `summary`, `price`, `sort_order`)
VALUES
    (1, 'Basic Service',     'basic-service',     'Quick health check and essential top-ups to keep your car running smoothly.',  2499.00, 10),
    (2, 'Standard Service',  'standard-service',  'Comprehensive periodic maintenance - recommended every 6 months / 10,000 km.', 4999.00, 20),
    (3, 'Premium Service',   'premium-service',   'Full deep-dive servicing including AC, brakes and interior detailing.',        8499.00, 30),
    (4, 'AC Service Special','ac-service',        'Dedicated air-conditioning service - gas top-up, leak check, vent clean.',     1999.00, 40)
ON DUPLICATE KEY UPDATE
    `name`       = VALUES(`name`),
    `summary`    = VALUES(`summary`),
    `price`      = VALUES(`price`),
    `sort_order` = VALUES(`sort_order`);

INSERT INTO `service_package_features` (`package_id`, `feature_text`, `sort_order`) VALUES
    -- Basic
    (1, 'Engine oil top-up', 10),
    (1, 'Air filter cleaning', 20),
    (1, 'Battery health check', 30),
    (1, 'Tyre pressure check', 40),
    (1, '15-point safety inspection', 50),
    -- Standard
    (2, 'Engine oil & filter change', 10),
    (2, 'Air filter replacement', 20),
    (2, 'Coolant top-up', 30),
    (2, 'Brake inspection', 40),
    (2, 'Battery & alternator check', 50),
    (2, 'Wheel alignment check', 60),
    (2, 'Exterior wash + interior vacuum', 70),
    -- Premium
    (3, 'Everything in Standard', 10),
    (3, 'AC gas top-up & vent cleaning', 20),
    (3, 'Brake pad check + change if needed', 30),
    (3, 'Spark plug inspection', 40),
    (3, '3-stage interior deep cleaning', 50),
    (3, 'Body polish + light dent rub-off', 60),
    -- AC Special
    (4, 'AC gas top-up', 10),
    (4, 'AC compressor inspection', 20),
    (4, 'Cabin filter clean / replace', 30),
    (4, 'Vent deodorising', 40),
    (4, 'Cooling performance test', 50);

-- ---------------------------------------------------------------------------
-- Default admin
-- ---------------------------------------------------------------------------
-- Skipped in seed.sql so we never ship a known password hash. Create the
-- first admin via the CLI installer (correct bcrypt hash generated by PHP):
--   php public/index.php cli/install create_admin admin@yourmechaniconline.com
-- See README.md for details.

-- ---------------------------------------------------------------------------
-- Default settings
-- ---------------------------------------------------------------------------
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES
    ('reminder_months', '4'),
    ('review_days',     '3'),
    ('allow_login_otp', '0'),
    ('require_email_otp', '0'),
    ('booking_notify_email', 'admin@yourmechaniconline.com')
ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
