#!/usr/bin/env bash
# Install nginx site + Let's Encrypt certs for marketing (@ + www).
# Does NOT modify booking/admin nginx (separate sites-enabled file).
#
# Usage (on VPS as root, after GoDaddy DNS cutover):
#   sudo bash deploy/scripts/setup-nginx-marketing.sh yourmechaniconline.com www.yourmechaniconline.com
#
# Prerequisites:
#   - booking/admin nginx already running (setup-nginx.sh)
#   - A records: @ and www → this server's public IP
#   - .env: YMO_MARKETING_APP_URL=https://www.yourmechaniconline.com
#           YMO_TRUST_PROXY_HEADERS=1
set -euo pipefail

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "Run as root: sudo bash $0 apex.example.com www.example.com" >&2
  exit 1
fi

APEX_HOST="${1:-}"
WWW_HOST="${2:-}"

if [[ -z "$APEX_HOST" || -z "$WWW_HOST" ]]; then
  echo "Usage: sudo bash $0 yourmechaniconline.com www.yourmechaniconline.com" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SITE_NAME="ymo-marketing"
AVAILABLE="/etc/nginx/sites-available/${SITE_NAME}"
ENABLED="/etc/nginx/sites-enabled/${SITE_NAME}"
WEBROOT="/var/www/html"
APP_UPSTREAM="127.0.0.1:8080"

mkdir -p "${WEBROOT}/.well-known/acme-challenge"
chown -R www-data:www-data /var/www/html 2>/dev/null || true

ensure_letsencrypt_nginx_snippets() {
  mkdir -p /etc/letsencrypt
  local opts="/etc/letsencrypt/options-ssl-nginx.conf"
  local dh="/etc/letsencrypt/ssl-dhparams.pem"
  local bundled_opts="${ROOT}/deploy/nginx/options-ssl-nginx.conf"
  local bundled_dh="${ROOT}/deploy/nginx/ssl-dhparams.pem"
  local certbot_raw="https://raw.githubusercontent.com/certbot/certbot/master"

  if [[ ! -f "$opts" ]]; then
    echo "==> Installing ${opts}..."
    if [[ -f "$bundled_opts" ]]; then
      cp "$bundled_opts" "$opts"
    else
      curl -fsSL "${certbot_raw}/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf" -o "$opts"
    fi
  fi
  if [[ ! -f "$dh" ]]; then
    echo "==> Installing ${dh}..."
    if [[ -f "$bundled_dh" ]]; then
      cp "$bundled_dh" "$dh"
    else
      curl -fsSL "${certbot_raw}/certbot/certbot/ssl-dhparams.pem" -o "$dh"
    fi
  fi
}

write_http_config() {
  cat > "$AVAILABLE" <<NGINX
# Marketing site — generated by setup-nginx-marketing.sh
# Proxy direct to loopback (booking/admin site defines upstream ymo_app separately).

server {
    listen 80;
    listen [::]:80;
    server_name ${APEX_HOST};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        return 301 https://${WWW_HOST}\$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name ${WWW_HOST};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_pass http://${APP_UPSTREAM};
    }
}
NGINX
}

write_tls_config() {
  local cert_dir="$1"
  cat > "$AVAILABLE" <<NGINX
# Marketing site — generated by setup-nginx-marketing.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${APEX_HOST} ${WWW_HOST};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        return 301 https://${WWW_HOST}\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${APEX_HOST};

    ssl_certificate ${cert_dir}/fullchain.pem;
    ssl_certificate_key ${cert_dir}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://${WWW_HOST}\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${WWW_HOST};

    ssl_certificate ${cert_dir}/fullchain.pem;
    ssl_certificate_key ${cert_dir}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 16M;

    include ${ROOT}/deploy/nginx/security-headers.conf;
    include ${ROOT}/deploy/nginx/static-assets.conf;

    location / {
        add_header Cache-Control "no-cache, must-revalidate" always;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_pass http://${APP_UPSTREAM};
    }
}
NGINX
}

echo "==> Checking DNS (@ and www must point to this server)..."
VPS_IP="$(curl -fsS --max-time 5 ifconfig.me 2>/dev/null || curl -fsS --max-time 5 icanhazip.com 2>/dev/null || true)"
for host in "$APEX_HOST" "$WWW_HOST"; do
  RESOLVED="$(getent ahostsv4 "$host" 2>/dev/null | awk '{print $1; exit}' || true)"
  if [[ -z "$RESOLVED" ]]; then
    echo "ERROR: No A record for ${host} (NXDOMAIN or not propagated yet)." >&2
    echo "Add GoDaddy A records: @ and www → your VPS IP (${VPS_IP:-same as booking})." >&2
    echo "See deploy/GODADDY_DNS.md" >&2
    exit 1
  fi
  if [[ -n "$VPS_IP" && "$RESOLVED" != "$VPS_IP" ]]; then
    echo "WARN: ${host} → ${RESOLVED} (this server is ${VPS_IP}). Certbot may fail if wrong." >&2
  else
    echo "  OK ${host} → ${RESOLVED}"
  fi
done

echo "==> Writing HTTP nginx config for marketing..."
write_http_config
ln -sf "$AVAILABLE" "$ENABLED"
nginx -t
systemctl reload nginx

CERT_NAME="${WWW_HOST}"
echo "==> Obtaining Let's Encrypt certificate (webroot)..."
if certbot certificates 2>/dev/null | grep -q "Certificate Name: ${CERT_NAME}\|Domains:.*${WWW_HOST}"; then
  echo "  Certificate already issued — skipping certbot."
else
  certbot certonly --webroot -w "$WEBROOT" \
    -d "$APEX_HOST" -d "$WWW_HOST" \
    --cert-name "$CERT_NAME" \
    --non-interactive --agree-tos \
    --register-unsafely-without-email
fi

CERT_DIR="/etc/letsencrypt/live/${CERT_NAME}"
if [[ ! -f "${CERT_DIR}/fullchain.pem" ]]; then
  CERT_DIR="$(find /etc/letsencrypt/live -mindepth 1 -maxdepth 1 -type d ! -name 'README' -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2- || true)"
fi
if [[ ! -f "${CERT_DIR}/fullchain.pem" ]]; then
  echo "ERROR: Certificate not found after certbot." >&2
  exit 1
fi

echo "==> Enabling TLS for marketing..."
ensure_letsencrypt_nginx_snippets
write_tls_config "$CERT_DIR"
nginx -t
systemctl reload nginx

echo ""
echo "Marketing TLS configured. Verify:"
echo "  curl -I https://${WWW_HOST}/"
echo "  curl -I https://${APEX_HOST}/   # should 301 → www"
echo ""
echo "Ensure .env has:"
echo "  YMO_MARKETING_APP_URL=https://${WWW_HOST}"
echo "  YMO_TRUST_PROXY_HEADERS=1"
echo "  CI_ENV=production"
echo ""
echo "Then restart app:"
echo "  cd /opt/ymo-codeigniter && docker compose -f docker-compose.yml -f deploy/docker-compose.vps.yml -f deploy/docker-compose.prod.yml restart app"
echo ""
echo "Smoke test:"
echo "  https://${WWW_HOST}/"
echo "  https://${WWW_HOST}/services/car-brake-repair"
echo "  https://${WWW_HOST}/contact-us"
echo "  Book now → https://booking.yourmechaniconline.com/packages"
