<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/** Auto-generated city hub + service pages - run generate_city_service_pages.py */
return array(
    'locations/indore' => array(
        'title' => 'Car Servicing in Indore - Your Mechanic Online',
        'meta_description' => 'Book expert car servicing in Indore - AC repair, denting, periodic service, and more. Free pick-up, transparent pricing. Call +91-7744-065904.',
        'h1' => 'Car servicing in Indore',
        'intro' => 'Professional car care with doorstep pick-up across Indore.',
        'service_catalog' => TRUE,
        'service_catalog_heading' => 'Car services in Indore',
        'body' => '<p class="ymo-quick-answer"><strong>Best car servicing in Indore?</strong> Your Mechanic Online is among the best car service providers in Indore, offering affordable denting, painting, AC repair, periodic servicing, and free pick-up/drop with transparent pricing.</p><h2>Areas we serve in Indore</h2><p>We provide free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54, AB Road, Nipania, and surrounding neighbourhoods.</p><h2>Frequently asked questions</h2><ul class="accordion margin-top-40"><li><div><h3>What is the cost of car servicing in Indore?</h3></div><div class="clearfix"><p>Car servicing in Indore starts from ₹1999 for periodic maintenance. YMO shares upfront estimates for denting, AC repair, and other jobs before starting work.</p></div></li><li><div><h3>Do you provide same-day car service in Indore?</h3></div><div class="clearfix"><p>Yes. Most maintenance and repair jobs are completed the same day. Book online or call +91-7744-065904.</p></div></li><li><div><h3>Which areas in Indore do you serve?</h3></div><div class="clearfix"><p>We serve Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54, AB Road, Nipania, and surrounding Indore areas with free pick-up and drop.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div><p><a href="/services">View all services</a> · <a href="/contact-us">Contact us</a></p>',
        'page_type' => 'hub',
        'city_slug' => 'indore',
        'quick_answer' => 'Your Mechanic Online is among the best car service providers in Indore, offering affordable denting, painting, AC repair, periodic servicing, and free pick-up/drop with transparent pricing.',
        'faq' => array(
            array('q' => 'What is the cost of car servicing in Indore?', 'a' => 'Car servicing in Indore starts from ₹1999 for periodic maintenance. YMO shares upfront estimates for denting, AC repair, and other jobs before starting work.'),
            array('q' => 'Do you provide same-day car service in Indore?', 'a' => 'Yes. Most maintenance and repair jobs are completed the same day. Book online or call +91-7744-065904.'),
            array('q' => 'Which areas in Indore do you serve?', 'a' => 'We serve Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54, AB Road, Nipania, and surrounding Indore areas with free pick-up and drop.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/complete-car-servicing-in-indore' => array(
        'title' => 'Complete Car Servicing in Indore @ ₹1999 - Your Mechanic Online',
        'meta_description' => 'Complete Car Servicing in Indore starting from ₹1999. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Complete Car Servicing in Indore',
        'intro' => 'Periodic maintenance with oil and filter changes, brake cleaning, AC filter service, coolant top-up, and interior vacuum - with free pick-up and delivery.',
        'body' => '<p class="ymo-quick-answer"><strong>Complete Car Servicing in Indore?</strong> Your Mechanic Online offers complete car servicing in Indore starting from ₹1999 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Periodic maintenance with oil and filter changes, brake cleaning, AC filter service, coolant top-up, and interior vacuum - with free pick-up and delivery.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does complete car servicing cost in Indore?</h3></div><div class="clearfix"><p>Pricing starting from ₹1999. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for complete car servicing in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'complete-car-servicing',
        'quick_answer' => 'Your Mechanic Online offers complete car servicing in Indore starting from ₹1999 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does complete car servicing cost in Indore?', 'a' => 'Pricing starting from ₹1999. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for complete car servicing in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-air-conditioner-servicing-in-indore' => array(
        'title' => 'Car Air Conditioner Servicing in Indore - Your Mechanic Online',
        'meta_description' => 'Car Air Conditioner Servicing in Indore. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Air Conditioner Servicing in Indore',
        'intro' => 'AC gas recharge, leak test, compressor check, and filter cleaning for reliable cooling.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Air Conditioner Servicing in Indore?</strong> Your Mechanic Online offers car air conditioner servicing in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>AC gas recharge, leak test, compressor check, and filter cleaning for reliable cooling.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car air conditioner servicing cost in Indore?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car air conditioner servicing in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'ac',
        'quick_answer' => 'Your Mechanic Online offers car air conditioner servicing in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car air conditioner servicing cost in Indore?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car air conditioner servicing in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-brake-repair-in-indore' => array(
        'title' => 'Car Brake Repair in Indore - Your Mechanic Online',
        'meta_description' => 'Car Brake Repair in Indore. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Brake Repair in Indore',
        'intro' => 'Brake pads, rotors, calipers, and fluid inspection and replacement by trained technicians.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Brake Repair in Indore?</strong> Your Mechanic Online offers car brake repair in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Brake pads, rotors, calipers, and fluid inspection and replacement by trained technicians.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car brake repair cost in Indore?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car brake repair in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'brakes',
        'quick_answer' => 'Your Mechanic Online offers car brake repair in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car brake repair cost in Indore?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car brake repair in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-denting-and-painting-in-indore-3000' => array(
        'title' => 'Car Denting And Painting in Indore @ ₹3000 - Your Mechanic Online',
        'meta_description' => 'Car Denting And Painting in Indore starting from ₹3000. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Denting And Painting in Indore',
        'intro' => 'Panel dent repair and industry-approved paint from ₹3000 per panel with colour matching.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Denting And Painting in Indore?</strong> Your Mechanic Online offers car denting and painting in Indore starting from ₹3000 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Panel dent repair and industry-approved paint from ₹3000 per panel with colour matching.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car denting and painting cost in Indore?</h3></div><div class="clearfix"><p>Pricing starting from ₹3000. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car denting and painting in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'denting',
        'quick_answer' => 'Your Mechanic Online offers car denting and painting in Indore starting from ₹3000 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car denting and painting cost in Indore?', 'a' => 'Pricing starting from ₹3000. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car denting and painting in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-engine-services-in-indore' => array(
        'title' => 'Car Engine Services in Indore - Your Mechanic Online',
        'meta_description' => 'Car Engine Services in Indore. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Engine Services in Indore',
        'intro' => 'Engine diagnostics, tune-ups, belt replacement, and major repair with expert mechanics.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Engine Services in Indore?</strong> Your Mechanic Online offers car engine services in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Engine diagnostics, tune-ups, belt replacement, and major repair with expert mechanics.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car engine services cost in Indore?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car engine services in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'engine',
        'quick_answer' => 'Your Mechanic Online offers car engine services in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car engine services cost in Indore?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car engine services in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-interior-cleaning-in-indore-2500' => array(
        'title' => 'Car Interior Deep Cleaning in Indore @ ₹2500 - Your Mechanic Online',
        'meta_description' => 'Car Interior Deep Cleaning in Indore starting from ₹2500. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Interior Deep Cleaning in Indore',
        'intro' => 'Vacuum, seat cleaning, dashboard polish, and odour removal from ₹2500.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Interior Deep Cleaning in Indore?</strong> Your Mechanic Online offers car interior deep cleaning in Indore starting from ₹2500 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Vacuum, seat cleaning, dashboard polish, and odour removal from ₹2500.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car interior deep cleaning cost in Indore?</h3></div><div class="clearfix"><p>Pricing starting from ₹2500. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car interior deep cleaning in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'interior',
        'quick_answer' => 'Your Mechanic Online offers car interior deep cleaning in Indore starting from ₹2500 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car interior deep cleaning cost in Indore?', 'a' => 'Pricing starting from ₹2500. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car interior deep cleaning in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-rubbing-and-polishing-in-indore-6500' => array(
        'title' => '3 Stage Rubbing and Polishing in Indore @ ₹6500 - Your Mechanic Online',
        'meta_description' => '3 Stage Rubbing and Polishing in Indore starting from ₹6500. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => '3 Stage Rubbing and Polishing in Indore',
        'intro' => 'Restore gloss and remove fine scratches with a professional 3-stage polish from ₹6500.',
        'body' => '<p class="ymo-quick-answer"><strong>3 Stage Rubbing and Polishing in Indore?</strong> Your Mechanic Online offers 3 stage rubbing and polishing in Indore starting from ₹6500 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Restore gloss and remove fine scratches with a professional 3-stage polish from ₹6500.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does 3 stage rubbing and polishing cost in Indore?</h3></div><div class="clearfix"><p>Pricing starting from ₹6500. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for 3 stage rubbing and polishing in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'polishing',
        'quick_answer' => 'Your Mechanic Online offers 3 stage rubbing and polishing in Indore starting from ₹6500 with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does 3 stage rubbing and polishing cost in Indore?', 'a' => 'Pricing starting from ₹6500. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for 3 stage rubbing and polishing in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/belts-and-hoses-in-indore' => array(
        'title' => 'Belts and Hoses in Indore - Your Mechanic Online',
        'meta_description' => 'Belts and Hoses in Indore. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Belts and Hoses in Indore',
        'intro' => 'Cooling system pressure test, hose replacement, and belt inspection.',
        'body' => '<p class="ymo-quick-answer"><strong>Belts and Hoses in Indore?</strong> Your Mechanic Online offers belts and hoses in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Cooling system pressure test, hose replacement, and belt inspection.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does belts and hoses cost in Indore?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for belts and hoses in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'belts',
        'quick_answer' => 'Your Mechanic Online offers belts and hoses in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does belts and hoses cost in Indore?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for belts and hoses in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/lube-oil-and-filters-in-indore' => array(
        'title' => 'Lube, Oil and Filters in Indore - Your Mechanic Online',
        'meta_description' => 'Lube, Oil and Filters in Indore. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Lube, Oil and Filters in Indore',
        'intro' => 'Engine oil change, transmission fluid, and filter replacement for all car types.',
        'body' => '<p class="ymo-quick-answer"><strong>Lube, Oil and Filters in Indore?</strong> Your Mechanic Online offers lube, oil and filters in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Engine oil change, transmission fluid, and filter replacement for all car types.</p><h3>Areas we serve in Indore</h3><p>Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54 and nearby areas.</p><h3>Related services</h3><p><a href="/locations/indore">All car services in Indore</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does lube, oil and filters cost in Indore?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for lube, oil and filters in Indore?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Indore.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Indore</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Indore.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'indore',
        'service_key' => 'lube',
        'quick_answer' => 'Your Mechanic Online offers lube, oil and filters in Indore with free pick-up and drop across Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does lube, oil and filters cost in Indore?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for lube, oil and filters in Indore?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Indore.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'locations/nashik' => array(
        'title' => 'Car Servicing in Nashik - Your Mechanic Online',
        'meta_description' => 'Book expert car servicing in Nashik - AC repair, denting, periodic service, and more. Free pick-up, transparent pricing. Call +91-7744-065904.',
        'h1' => 'Car servicing in Nashik',
        'intro' => 'Professional car care with doorstep pick-up across Nashik.',
        'service_catalog' => TRUE,
        'service_catalog_heading' => 'Car services in Nashik',
        'body' => '<p class="ymo-quick-answer"><strong>Best car servicing in Nashik?</strong> Your Mechanic Online provides expert car servicing and repairs in Nashik with trained mechanics, transparent pricing, and doorstep pick-up across College Road, Nashik Road, Uday Nagar, and surrounding areas.</p><h2>Areas we serve in Nashik</h2><p>We provide free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar, Ojhar, Panchavati, and surrounding neighbourhoods.</p><h2>Frequently asked questions</h2><ul class="accordion margin-top-40"><li><div><h3>Where can I find a reliable car mechanic in Nashik?</h3></div><div class="clearfix"><p>Your Mechanic Online offers trained mechanics, modern diagnostic equipment, and upfront pricing for car repair and servicing across Nashik.</p></div></li><li><div><h3>Do you serve Nashik Road and College Road?</h3></div><div class="clearfix"><p>Yes. We provide free pick-up and drop from Nashik Road, College Road, Uday Nagar, Indira Nagar, Vidya Nagar, and nearby neighbourhoods.</p></div></li><li><div><h3>What car services are available in Nashik?</h3></div><div class="clearfix"><p>Complete servicing, AC repair, brake repair, denting and painting, engine diagnostics, interior cleaning, rubbing and polishing, belts and hoses, and oil changes.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div><p><a href="/services">View all services</a> · <a href="/contact-us">Contact us</a></p>',
        'page_type' => 'hub',
        'city_slug' => 'nashik',
        'quick_answer' => 'Your Mechanic Online provides expert car servicing and repairs in Nashik with trained mechanics, transparent pricing, and doorstep pick-up across College Road, Nashik Road, Uday Nagar, and surrounding areas.',
        'faq' => array(
            array('q' => 'Where can I find a reliable car mechanic in Nashik?', 'a' => 'Your Mechanic Online offers trained mechanics, modern diagnostic equipment, and upfront pricing for car repair and servicing across Nashik.'),
            array('q' => 'Do you serve Nashik Road and College Road?', 'a' => 'Yes. We provide free pick-up and drop from Nashik Road, College Road, Uday Nagar, Indira Nagar, Vidya Nagar, and nearby neighbourhoods.'),
            array('q' => 'What car services are available in Nashik?', 'a' => 'Complete servicing, AC repair, brake repair, denting and painting, engine diagnostics, interior cleaning, rubbing and polishing, belts and hoses, and oil changes.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/complete-car-servicing-in-nashik' => array(
        'title' => 'Complete Car Servicing in Nashik @ ₹1999 - Your Mechanic Online',
        'meta_description' => 'Complete Car Servicing in Nashik starting from ₹1999. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Complete Car Servicing in Nashik',
        'intro' => 'Periodic maintenance with oil and filter changes, brake cleaning, AC filter service, coolant top-up, and interior vacuum - with free pick-up and delivery.',
        'body' => '<p class="ymo-quick-answer"><strong>Complete Car Servicing in Nashik?</strong> Your Mechanic Online offers complete car servicing in Nashik starting from ₹1999 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Periodic maintenance with oil and filter changes, brake cleaning, AC filter service, coolant top-up, and interior vacuum - with free pick-up and delivery.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does complete car servicing cost in Nashik?</h3></div><div class="clearfix"><p>Pricing starting from ₹1999. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for complete car servicing in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'complete-car-servicing',
        'quick_answer' => 'Your Mechanic Online offers complete car servicing in Nashik starting from ₹1999 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does complete car servicing cost in Nashik?', 'a' => 'Pricing starting from ₹1999. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for complete car servicing in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-air-conditioner-servicing-in-nashik' => array(
        'title' => 'Car Air Conditioner Servicing in Nashik - Your Mechanic Online',
        'meta_description' => 'Car Air Conditioner Servicing in Nashik. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Air Conditioner Servicing in Nashik',
        'intro' => 'AC gas recharge, leak test, compressor check, and filter cleaning for reliable cooling.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Air Conditioner Servicing in Nashik?</strong> Your Mechanic Online offers car air conditioner servicing in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>AC gas recharge, leak test, compressor check, and filter cleaning for reliable cooling.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car air conditioner servicing cost in Nashik?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car air conditioner servicing in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'ac',
        'quick_answer' => 'Your Mechanic Online offers car air conditioner servicing in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car air conditioner servicing cost in Nashik?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car air conditioner servicing in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-brake-repair-in-nashik' => array(
        'title' => 'Car Brake Repair in Nashik - Your Mechanic Online',
        'meta_description' => 'Car Brake Repair in Nashik. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Brake Repair in Nashik',
        'intro' => 'Brake pads, rotors, calipers, and fluid inspection and replacement by trained technicians.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Brake Repair in Nashik?</strong> Your Mechanic Online offers car brake repair in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Brake pads, rotors, calipers, and fluid inspection and replacement by trained technicians.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car brake repair cost in Nashik?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car brake repair in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'brakes',
        'quick_answer' => 'Your Mechanic Online offers car brake repair in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car brake repair cost in Nashik?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car brake repair in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-denting-and-painting-in-nashik-3000' => array(
        'title' => 'Car Denting And Painting in Nashik @ ₹3000 - Your Mechanic Online',
        'meta_description' => 'Car Denting And Painting in Nashik starting from ₹3000. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Denting And Painting in Nashik',
        'intro' => 'Panel dent repair and industry-approved paint from ₹3000 per panel with colour matching.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Denting And Painting in Nashik?</strong> Your Mechanic Online offers car denting and painting in Nashik starting from ₹3000 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Panel dent repair and industry-approved paint from ₹3000 per panel with colour matching.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car denting and painting cost in Nashik?</h3></div><div class="clearfix"><p>Pricing starting from ₹3000. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car denting and painting in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'denting',
        'quick_answer' => 'Your Mechanic Online offers car denting and painting in Nashik starting from ₹3000 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car denting and painting cost in Nashik?', 'a' => 'Pricing starting from ₹3000. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car denting and painting in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-engine-services-in-nashik' => array(
        'title' => 'Car Engine Services in Nashik - Your Mechanic Online',
        'meta_description' => 'Car Engine Services in Nashik. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Engine Services in Nashik',
        'intro' => 'Engine diagnostics, tune-ups, belt replacement, and major repair with expert mechanics.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Engine Services in Nashik?</strong> Your Mechanic Online offers car engine services in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Engine diagnostics, tune-ups, belt replacement, and major repair with expert mechanics.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car engine services cost in Nashik?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car engine services in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'engine',
        'quick_answer' => 'Your Mechanic Online offers car engine services in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car engine services cost in Nashik?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car engine services in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-interior-cleaning-in-nashik-2500' => array(
        'title' => 'Car Interior Deep Cleaning in Nashik @ ₹2500 - Your Mechanic Online',
        'meta_description' => 'Car Interior Deep Cleaning in Nashik starting from ₹2500. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Car Interior Deep Cleaning in Nashik',
        'intro' => 'Vacuum, seat cleaning, dashboard polish, and odour removal from ₹2500.',
        'body' => '<p class="ymo-quick-answer"><strong>Car Interior Deep Cleaning in Nashik?</strong> Your Mechanic Online offers car interior deep cleaning in Nashik starting from ₹2500 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Vacuum, seat cleaning, dashboard polish, and odour removal from ₹2500.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does car interior deep cleaning cost in Nashik?</h3></div><div class="clearfix"><p>Pricing starting from ₹2500. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for car interior deep cleaning in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'interior',
        'quick_answer' => 'Your Mechanic Online offers car interior deep cleaning in Nashik starting from ₹2500 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does car interior deep cleaning cost in Nashik?', 'a' => 'Pricing starting from ₹2500. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for car interior deep cleaning in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/car-rubbing-and-polishing-in-nashik-6500' => array(
        'title' => '3 Stage Rubbing and Polishing in Nashik @ ₹6500 - Your Mechanic Online',
        'meta_description' => '3 Stage Rubbing and Polishing in Nashik starting from ₹6500. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => '3 Stage Rubbing and Polishing in Nashik',
        'intro' => 'Restore gloss and remove fine scratches with a professional 3-stage polish from ₹6500.',
        'body' => '<p class="ymo-quick-answer"><strong>3 Stage Rubbing and Polishing in Nashik?</strong> Your Mechanic Online offers 3 stage rubbing and polishing in Nashik starting from ₹6500 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Restore gloss and remove fine scratches with a professional 3-stage polish from ₹6500.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does 3 stage rubbing and polishing cost in Nashik?</h3></div><div class="clearfix"><p>Pricing starting from ₹6500. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for 3 stage rubbing and polishing in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'polishing',
        'quick_answer' => 'Your Mechanic Online offers 3 stage rubbing and polishing in Nashik starting from ₹6500 with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does 3 stage rubbing and polishing cost in Nashik?', 'a' => 'Pricing starting from ₹6500. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for 3 stage rubbing and polishing in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/belts-and-hoses-in-nashik' => array(
        'title' => 'Belts and Hoses in Nashik - Your Mechanic Online',
        'meta_description' => 'Belts and Hoses in Nashik. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Belts and Hoses in Nashik',
        'intro' => 'Cooling system pressure test, hose replacement, and belt inspection.',
        'body' => '<p class="ymo-quick-answer"><strong>Belts and Hoses in Nashik?</strong> Your Mechanic Online offers belts and hoses in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Cooling system pressure test, hose replacement, and belt inspection.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does belts and hoses cost in Nashik?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for belts and hoses in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'belts',
        'quick_answer' => 'Your Mechanic Online offers belts and hoses in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does belts and hoses cost in Nashik?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for belts and hoses in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
    'services/lube-oil-and-filters-in-nashik' => array(
        'title' => 'Lube, Oil and Filters in Nashik - Your Mechanic Online',
        'meta_description' => 'Lube, Oil and Filters in Nashik. Expert mechanics, transparent pricing, free pick-up. Book with Your Mechanic Online.',
        'h1' => 'Lube, Oil and Filters in Nashik',
        'intro' => 'Engine oil change, transmission fluid, and filter replacement for all car types.',
        'body' => '<p class="ymo-quick-answer"><strong>Lube, Oil and Filters in Nashik?</strong> Your Mechanic Online offers lube, oil and filters in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.</p><h3>SERVICE OVERVIEW</h3><p>Engine oil change, transmission fluid, and filter replacement for all car types.</p><h3>Areas we serve in Nashik</h3><p>College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar and nearby areas.</p><h3>Related services</h3><p><a href="/locations/nashik">All car services in Nashik</a> · <a href="/services">Service catalogue</a></p><h3>Popular questions</h3><ul class="accordion margin-top-40"><li><div><h3>How much does lube, oil and filters cost in Nashik?</h3></div><div class="clearfix"><p>Pricing varies by vehicle. YMO provides upfront estimates before work begins.</p></div></li><li><div><h3>Do you offer pick-up for lube, oil and filters in Nashik?</h3></div><div class="clearfix"><p>Yes. Free doorstep pick-up and delivery is available across Nashik.</p></div></li></ul><div class="md-card-filled p-4 my-4 ymo-nap-block"><h3 class="md-title-md">Contact YMO - Nashik</h3><p class="mb-1"><strong>Phone:</strong> <a href="tel:+917744065904">+91-7744-065904</a></p><p class="mb-1"><strong>Email:</strong> <a href="mailto:contactus@yourmechaniconline.com">contactus@yourmechaniconline.com</a></p><p class="mb-0"><strong>Service area:</strong> Doorstep pick-up and drop across Nashik.</p></div>',
        'page_type' => 'service',
        'city_slug' => 'nashik',
        'service_key' => 'lube',
        'quick_answer' => 'Your Mechanic Online offers lube, oil and filters in Nashik with free pick-up and drop across College Road, Nashik Road, Uday Nagar, Indira Nagar, Vidya Nagar, Ashwamegh Nagar. Book online or call +91-7744-065904.',
        'faq' => array(
            array('q' => 'How much does lube, oil and filters cost in Nashik?', 'a' => 'Pricing varies by vehicle. YMO provides upfront estimates before work begins.'),
            array('q' => 'Do you offer pick-up for lube, oil and filters in Nashik?', 'a' => 'Yes. Free doorstep pick-up and delivery is available across Nashik.'),
        ),
        'updated_at' => '2026-07-20',
        'og_image' => '/assets/img/marketing/revslider/main/image_01.jpg',
        'view' => 'marketing/page',
    ),
);
