<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * City / locality / service matrix for SEO hub-and-spoke architecture.
 * NAP blocks should match Google Business Profile listings per city.
 */
return array(
    'pune' => array(
        'name'       => 'Pune',
        'slug'       => 'pune',
        'hub_path'   => 'locations/pune',
        'phone'      => '+91-7744-065904',
        'email'      => 'contactus@yourmechaniconline.com',
        'gbp_url'    => 'https://share.google/zdztabyzbml7l1uvZ',
        'address'    => array(
            '@type'           => 'PostalAddress',
            'addressLocality' => 'Pune',
            'addressRegion'   => 'Maharashtra',
            'addressCountry'  => 'IN',
        ),
        'geo'        => array('latitude' => '18.5204', 'longitude' => '73.8567'),
        'geo_match'  => array(
            'cities' => array('Pune', 'Pimpri', 'Chinchwad'),
        ),
        'hero_image' => 'revslider/main/image_01.jpg',
        'localities' => array(
            'baner'       => array('label' => 'Baner', 'slug' => 'the-best-car-servicing-in-baner'),
            'wakad'       => array('label' => 'Wakad', 'slug' => 'affordable-car-servicing-in-wakad-pune'),
            'hinjewadi'   => array('label' => 'Hinjewadi', 'slug' => 'best-car-services-hinjewadi-pune'),
            'aundh'       => array('label' => 'Aundh', 'slug' => 'car-servicing-in-aundh'),
            'bavdhan'     => array('label' => 'Bavdhan', 'slug' => 'best-car-servicing-in-bavdhan-pune-expert-care'),
            'viman_nagar' => array('label' => 'Viman Nagar', 'slug' => 'affordable-car-services-viman-nagar-pune'),
        ),
        'neighborhoods' => array('Baner', 'Wakad', 'Hinjewadi', 'Aundh', 'Bavdhan', 'Viman Nagar', 'Warje', 'Kothrud', 'Hadapsar', 'Kharadi'),
        'quick_answer' => 'Your Mechanic Online offers doorstep car servicing across Pune with free pick-up and drop, transparent pricing from ₹1999, and nine specialist services covering Baner, Wakad, Hinjewadi, Aundh, Bavdhan, and Viman Nagar.',
        'faq' => array(
            array('q' => 'What is the cost of car servicing in Pune?', 'a' => 'Complete car servicing in Pune starts from ₹1999. Rubbing and polishing packages start at ₹6500 and interior deep cleaning from ₹2500. YMO provides upfront estimates before work begins.'),
            array('q' => 'Does YMO offer doorstep pick-up in Pune?', 'a' => 'Yes. We provide free doorstep pick-up and delivery across Pune including Baner, Wakad, Hinjewadi, Aundh, Bavdhan, and Viman Nagar.'),
        ),
    ),
    'indore' => array(
        'name'       => 'Indore',
        'slug'       => 'indore',
        'hub_path'   => 'locations/indore',
        'legacy_hub' => 'bestcar-services-indore-affordable-solutions',
        'phone'      => '+91-7744-065904',
        'email'      => 'contactus@yourmechaniconline.com',
        'gbp_url'    => '',
        'address'    => array(
            '@type'           => 'PostalAddress',
            'addressLocality' => 'Indore',
            'addressRegion'   => 'Madhya Pradesh',
            'addressCountry'  => 'IN',
        ),
        'geo'        => array('latitude' => '22.7196', 'longitude' => '75.8577'),
        'geo_match'  => array(
            'cities'  => array('Indore'),
            'regions' => array('Madhya Pradesh'),
        ),
        'hero_image' => '2022/03/974159.jpg',
        'localities' => array(),
        'neighborhoods' => array('Deoguradia', 'Vijay Nagar', 'Palasia', 'Bhawarkua', 'Rau', 'Scheme 54', 'AB Road', 'Nipania'),
        'quick_answer' => 'Your Mechanic Online is among the best car service providers in Indore, offering affordable denting, painting, AC repair, periodic servicing, and free pick-up/drop with transparent pricing.',
        'faq' => array(
            array('q' => 'What is the cost of car servicing in Indore?', 'a' => 'Car servicing in Indore starts from ₹1999 for periodic maintenance. YMO shares upfront estimates for denting, AC repair, and other jobs before starting work.'),
            array('q' => 'Do you provide same-day car service in Indore?', 'a' => 'Yes. Most maintenance and repair jobs are completed the same day. Book online or call +91-7744-065904 for a free consultation.'),
            array('q' => 'Which areas in Indore do you serve?', 'a' => 'We serve Deoguradia, Vijay Nagar, Palasia, Bhawarkua, Rau, Scheme 54, AB Road, Nipania, and surrounding Indore areas with free pick-up and drop.'),
        ),
    ),
    'nashik' => array(
        'name'       => 'Nashik',
        'slug'       => 'nashik',
        'hub_path'   => 'locations/nashik',
        'phone'      => '+91-7744-065904',
        'email'      => 'contactus@yourmechaniconline.com',
        'gbp_url'    => '',
        'address'    => array(
            '@type'           => 'PostalAddress',
            'addressLocality' => 'Nashik',
            'addressRegion'   => 'Maharashtra',
            'addressCountry'  => 'IN',
        ),
        'geo'        => array('latitude' => '19.9975', 'longitude' => '73.7898'),
        'geo_match'  => array(
            'cities' => array('Nashik', 'Nasik'),
        ),
        'hero_image' => 'revslider/main/image_021.jpg',
        'localities' => array(),
        'neighborhoods' => array('College Road', 'Nashik Road', 'Uday Nagar', 'Indira Nagar', 'Vidya Nagar', 'Ashwamegh Nagar', 'Ojhar', 'Panchavati', 'Satpur', 'Gangapur Road'),
        'quick_answer' => 'Your Mechanic Online provides expert car servicing and repairs in Nashik with trained mechanics, transparent pricing, and doorstep pick-up across College Road, Nashik Road, Uday Nagar, and surrounding areas.',
        'faq' => array(
            array('q' => 'Where can I find a reliable car mechanic in Nashik?', 'a' => 'Your Mechanic Online offers trained mechanics, modern diagnostic equipment, and upfront pricing for car repair and servicing across Nashik.'),
            array('q' => 'Do you serve Nashik Road and College Road?', 'a' => 'Yes. We provide free pick-up and drop from Nashik Road, College Road, Uday Nagar, Indira Nagar, Vidya Nagar, and nearby neighbourhoods.'),
            array('q' => 'What car services are available in Nashik?', 'a' => 'Complete servicing, AC repair, brake repair, denting and painting, engine diagnostics, interior cleaning, rubbing and polishing, belts and hoses, and oil changes.'),
        ),
    ),
    'services' => array(
        array(
            'key'           => 'complete-car-servicing',
            'title'         => 'Complete Car Servicing',
            'icon'          => 'car_repair',
            'pune_slug'     => 'services/complete-car-servicing',
            'city_slug'     => 'services/complete-car-servicing-in-{city}',
            'price_from'    => 1999,
            'og_image'      => '/assets/img/marketing/2022/03/complete-car-servicing-in-pune-1-scaled.jpg',
            'overview'      => 'Periodic maintenance with oil and filter changes, brake cleaning, AC filter service, coolant top-up, and interior vacuum - with free pick-up and delivery.',
        ),
        array(
            'key'           => 'ac',
            'title'         => 'Car Air Conditioner Servicing',
            'icon'          => 'ac_unit',
            'pune_slug'     => 'services/car-air-conditioner-servicing-in-pune',
            'city_slug'     => 'services/car-air-conditioner-servicing-in-{city}',
            'price_from'    => null,
            'og_image'      => '/assets/img/marketing/revslider/main/image_01.jpg',
            'overview'      => 'AC gas recharge, leak test, compressor check, and filter cleaning for reliable cooling.',
        ),
        array(
            'key'           => 'brakes',
            'title'         => 'Car Brake Repair',
            'icon'          => 'report',
            'pune_slug'     => 'services/car-brake-repair',
            'city_slug'     => 'services/car-brake-repair-in-{city}',
            'price_from'    => null,
            'og_image'      => '/assets/img/marketing/2015/05/car-brake-repair-pune.jpg',
            'overview'      => 'Brake pads, rotors, calipers, and fluid inspection and replacement by trained technicians.',
        ),
        array(
            'key'           => 'denting',
            'title'         => 'Car Denting And Painting',
            'icon'          => 'auto_fix_high',
            'pune_slug'     => 'services/car-denting-and-painting-3000',
            'city_slug'     => 'services/car-denting-and-painting-in-{city}-3000',
            'price_from'    => 3000,
            'og_image'      => '/assets/img/marketing/2022/03/car-painting-in-pune.jpg',
            'overview'      => 'Panel dent repair and industry-approved paint from ₹3000 per panel with colour matching.',
        ),
        array(
            'key'           => 'engine',
            'title'         => 'Car Engine Services',
            'icon'          => 'settings',
            'pune_slug'     => 'services/car-engine-services-in-pune',
            'city_slug'     => 'services/car-engine-services-in-{city}',
            'price_from'    => null,
            'og_image'      => '/assets/img/marketing/2015/05/car-engine-servicing-pune-scaled.jpg',
            'overview'      => 'Engine diagnostics, tune-ups, belt replacement, and major repair with expert mechanics.',
        ),
        array(
            'key'           => 'interior',
            'title'         => 'Car Interior Deep Cleaning',
            'icon'          => 'vacuum',
            'pune_slug'     => 'services/car-interior-cleaning-in-pune-2500',
            'city_slug'     => 'services/car-interior-cleaning-in-{city}-2500',
            'price_from'    => 2500,
            'og_image'      => '/assets/img/marketing/2022/03/car-interior-cleaning-in-pune-scaled.jpg',
            'overview'      => 'Vacuum, seat cleaning, dashboard polish, and odour removal from ₹2500.',
        ),
        array(
            'key'           => 'polishing',
            'title'         => '3 Stage Rubbing and Polishing',
            'icon'          => 'cleaning_services',
            'pune_slug'     => 'services/car-rubbing-and-polishing-in-pune-6500',
            'city_slug'     => 'services/car-rubbing-and-polishing-in-{city}-6500',
            'price_from'    => 6500,
            'og_image'      => '/assets/img/marketing/2022/03/car-rubbing-and-polishing.jpg',
            'overview'      => 'Restore gloss and remove fine scratches with a professional 3-stage polish from ₹6500.',
        ),
        array(
            'key'           => 'belts',
            'title'         => 'Belts and Hoses',
            'icon'          => 'build',
            'pune_slug'     => 'services/belts-and-hoses',
            'city_slug'     => 'services/belts-and-hoses-in-{city}',
            'price_from'    => null,
            'og_image'      => '/assets/img/marketing/2022/04/car-belts-service-pune-scaled.jpg',
            'overview'      => 'Cooling system pressure test, hose replacement, and belt inspection.',
        ),
        array(
            'key'           => 'lube',
            'title'         => 'Lube, Oil and Filters',
            'icon'          => 'oil_barrel',
            'pune_slug'     => 'services/lube-oil-and-filters',
            'city_slug'     => 'services/lube-oil-and-filters-in-{city}',
            'price_from'    => null,
            'og_image'      => '/assets/img/marketing/2015/05/image_02.jpg',
            'overview'      => 'Engine oil change, transmission fluid, and filter replacement for all car types.',
        ),
    ),
);
