<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Brand definitions for SEO brand × city landing pages.
 * Add a row here → marketing_brand_pages() auto-generates live pages.
 */
return array(
    'maruti-suzuki' => array(
        'brand_name'    => 'Maruti Suzuki',
        'slug'          => 'maruti-suzuki',
        'common_models' => array('Swift', 'Baleno', 'Dzire', 'Brezza', 'Ertiga', 'Wagon R'),
        'intro_copy'    => 'Maruti Suzuki is India\'s largest car brand, and YMO technicians service Swift, Baleno, Dzire, and every Maruti model with genuine-spec parts, manufacturer-recommended intervals, and free doorstep pick-up.',
        'service_includes' => array(
            'Engine oil and filter change with Mobil-spec oil',
            'Brake cleaning, greasing, and pad inspection',
            'AC filter cleaning and cooling performance check',
            'Coolant, brake fluid, and battery-water top-up',
            'Full interior vacuum and exterior wash',
            'Multi-point inspection report with photos on WhatsApp',
        ),
        'common_issues' => array(
            'Swift / Baleno' => 'Clutch wear on city commutes, AC cooling drop in summer, and suspension noise on rough roads.',
            'Dzire / Ertiga' => 'Rear brake pad wear from taxi use, timing belt checks on high-mileage units, and AC compressor strain on long highway runs.',
            'Wagon R / Brezza' => 'CVT/AMT fluid checks, underbody rust prevention after monsoon, and headlamp fogging on older models.',
        ),
        'active'        => TRUE,
    ),
    'hyundai' => array(
        'brand_name'    => 'Hyundai',
        'slug'          => 'hyundai',
        'common_models' => array('i20', 'Creta', 'Venue', 'Verna', 'Grand i10', 'Alcazar'),
        'intro_copy'    => 'Hyundai owners in Pune, Indore, and Nashik trust YMO for i20, Creta, and Venue servicing — factory-grade diagnostics, transparent pricing from ₹1,999, and workshop capability for denting, AC, and engine work.',
        'service_includes' => array(
            'Synthetic or semi-synthetic oil change per Hyundai schedule',
            'Brake disc/pad inspection and fluid top-up',
            'AC gas pressure test and cabin filter service',
            'Tyre rotation and alignment check recommendation',
            'Battery health test and terminal cleaning',
            'Doorstep pick-up, service, and delivery',
        ),
        'common_issues' => array(
            'i20 / Grand i10' => 'Dual-clutch judder on DCT variants, AC condenser leaks, and rear suspension bush wear.',
            'Creta / Alcazar' => 'Turbo oil consumption checks, sunroof drain clogging, and brake squeal on early pad wear.',
            'Venue / Verna' => 'Infotainment software glitches, turbo intercooler hose checks, and paint chip repair on highway stone hits.',
        ),
        'active'        => TRUE,
    ),
    'tata' => array(
        'brand_name'    => 'Tata',
        'slug'          => 'tata',
        'common_models' => array('Nexon', 'Punch', 'Harrier', 'Safari', 'Tiago', 'Altroz'),
        'intro_copy'    => 'Tata Nexon, Punch, Harrier, and Tiago owners choose YMO for periodic service, EV-ready workshop practices, and body repair — with trained mechanics who understand Tata\'s safety-focused platform and turbo diesel engines.',
        'service_includes' => array(
            'Engine oil, filter, and air filter replacement',
            'Brake system inspection including ABS sensor check',
            'AC performance test and filter cleaning',
            'Underbody wash and rust-prevention check',
            'Suspension and steering linkage inspection',
            'Free pick-up and drop across your city',
        ),
        'common_issues' => array(
            'Nexon / Punch' => 'Turbo lag on diesel variants, infotainment connectivity resets, and rear wiper motor faults.',
            'Harrier / Safari' => 'AdBlue system checks on diesel, panoramic sunroof drain maintenance, and heavy brake wear on SUV weight.',
            'Tiago / Altroz' => 'Clutch cable adjustment on manual variants, AC blower noise, and door handle cable wear.',
        ),
        'active'        => TRUE,
    ),
    'honda' => array(
        'brand_name'    => 'Honda',
        'slug'          => 'honda',
        'common_models' => array('City', 'Amaze', 'Elevate', 'Jazz', 'WR-V'),
        'intro_copy'    => 'Honda City, Amaze, and Elevate servicing at YMO covers i-VTEC and i-DTEC engines with precision — CVT fluid checks, genuine-spec filters, and the workshop depth to handle denting and AC compressor work.',
        'service_includes' => array(
            'Engine oil change with Honda-recommended viscosity',
            'CVT / automatic transmission fluid level check',
            'Brake pad, rotor, and caliper inspection',
            'AC leak test and gas recharge if needed',
            'Spark plug and belt inspection on schedule',
            'Complimentary car wash and interior vacuum',
        ),
        'common_issues' => array(
            'City / Amaze' => 'CVT shudder on low-speed creep, AC cooling loss after 3+ years, and front strut mount noise.',
            'Elevate' => 'Turbo diesel DPF awareness, ADAS sensor calibration after body work, and alloy wheel corrosion.',
            'Jazz / WR-V' => 'Rear seat folding mechanism lubrication, fuel pump humming on high mileage, and paint fade on horizontal panels.',
        ),
        'active'        => TRUE,
    ),
    'mahindra' => array(
        'brand_name'    => 'Mahindra',
        'slug'          => 'mahindra',
        'common_models' => array('XUV700', 'Scorpio N', 'Thar', 'Bolero', 'XUV300', 'XUV400'),
        'intro_copy'    => 'Mahindra SUVs — XUV700, Scorpio, Thar, and Bolero — need robust servicing for diesel torque and off-road use. YMO provides heavy-duty brake checks, 4×4 component inspection, and body repair with industry-approved paints.',
        'service_includes' => array(
            'Diesel engine oil and fuel filter service',
            '4×4 transfer case and differential fluid check (where applicable)',
            'Turbocharger and intercooler hose inspection',
            'Heavy-duty brake pad and rotor assessment',
            'Underbody protection and mud-flap check',
            'Doorstep collection and return',
        ),
        'common_issues' => array(
            'XUV700 / Scorpio N' => 'AdBlue top-up, sunroof drain blockage, and turbo whistle on cold starts.',
            'Thar' => 'Hard-top seal leaks, clutch wear on off-road use, and aftermarket accessory wiring checks.',
            'Bolero / XUV300' => 'Leaf spring bushing wear, power steering pump noise, and AC condenser stone damage.',
        ),
        'active'        => TRUE,
    ),
    'toyota' => array(
        'brand_name'    => 'Toyota',
        'slug'          => 'toyota',
        'common_models' => array('Innova Crysta', 'Fortuner', 'Glanza', 'Urban Cruiser Hyryder', 'Camry'),
        'intro_copy'    => 'Toyota reliability deserves equally reliable service. YMO maintains Innova, Fortuner, and Hyryder with Toyota-spec oil intervals, hybrid system awareness on Hyryder, and luxury-grade attention on Fortuner and Camry.',
        'service_includes' => array(
            'Engine oil and filter per Toyota service schedule',
            'Hybrid battery cooling filter check (Hyryder / Camry hybrid)',
            'Brake fluid flush recommendation at interval',
            'AC disinfectant treatment and gas top-up',
            'Suspension bush and tie-rod end inspection',
            'Pick-up and delivery at your location',
        ),
        'common_issues' => array(
            'Innova Crysta' => 'Clutch and flywheel on diesel manual, AC rear vent weak airflow, and injector cleaning on high km.',
            'Fortuner' => '4×4 actuator service, turbo actuator faults, and heavy tyre wear alignment correction.',
            'Glanza / Hyryder' => 'Hybrid inverter coolant check, CVT fluid condition, and infotainment lag on older firmware.',
        ),
        'active'        => TRUE,
    ),
    'kia' => array(
        'brand_name'    => 'Kia',
        'slug'          => 'kia',
        'common_models' => array('Seltos', 'Sonet', 'Carens', 'EV6'),
        'intro_copy'    => 'Kia Seltos, Sonet, and Carens owners book YMO for turbo-petrol and diesel servicing, DCT fluid awareness, and warranty-friendly maintenance records — plus denting and polishing when city parking takes its toll.',
        'service_includes' => array(
            'Turbo engine oil change with correct grade',
            'DCT / automatic transmission inspection',
            'Brake system service including electronic parking brake check',
            'AC performance and cabin filter replacement',
            'Tyre pressure, tread, and alignment recommendation',
            'Free doorstep pick-up and drop',
        ),
        'common_issues' => array(
            'Seltos / Sonet' => 'DCT heat management on traffic crawls, turbo wastegate rattle, and panoramic sunroof creaks.',
            'Carens' => 'Third-row AC vent airflow, sliding door track lubrication, and rear brake pad wear on loaded trips.',
            'EV6' => 'High-voltage system checks by trained staff, brake regen calibration, and tyre rotation for even wear.',
        ),
        'active'        => TRUE,
    ),
    'volkswagen' => array(
        'brand_name'    => 'Volkswagen',
        'slug'          => 'volkswagen',
        'common_models' => array('Polo', 'Virtus', 'Taigun', 'Tiguan', 'Vento'),
        'intro_copy'    => 'Volkswagen Polo, Virtus, and Taigun TSI engines need exact oil specifications and diagnostic scans. YMO\'s workshop handles VAG-group servicing, DSG awareness, and body repair for German build quality cars.',
        'service_includes' => array(
            'VW-spec 502/505 or 504/507 approved oil change',
            'DSG mechatronic fluid level check (where applicable)',
            'Brake pad wear sensor reset and pad replacement',
            'AC regas with R1234yf or R134a as per model year',
            'OBD diagnostic scan for stored fault codes',
            'Doorstep service with pick-up and return',
        ),
        'common_issues' => array(
            'Polo / Vento' => 'DSG judder on low speed, window regulator failures, and EGR carbon on TDI.',
            'Virtus / Taigun' => 'Turbo oil line seepage, infotainment freeze, and alloy wheel kerb damage repair.',
            'Tiguan' => '4MOTION haldex service, panoramic roof drain, and adaptive cruise sensor alignment after bumper work.',
        ),
        'active'        => TRUE,
    ),
    'skoda' => array(
        'brand_name'    => 'Skoda',
        'slug'          => 'skoda',
        'common_models' => array('Slavia', 'Kushaq', 'Octavia', 'Superb', 'Kodiaq'),
        'intro_copy'    => 'Skoda Slavia, Kushaq, and Octavia owners rely on YMO for TSI/TDI servicing with VAG-compatible diagnostics, DSG maintenance awareness, and premium denting and painting when needed.',
        'service_includes' => array(
            'Skoda-approved engine oil and filter change',
            'DSG / automatic gearbox inspection',
            'Brake disc skim or pad replacement as needed',
            'AC system leak test and compressor check',
            'Coolant and brake fluid condition assessment',
            'Free pick-up and delivery',
        ),
        'common_issues' => array(
            'Slavia / Kushaq' => 'Turbo oil consumption monitoring, DSG mechatronic temperature warnings, and sunroof wind noise.',
            'Octavia / Superb' => 'Dual-clutch shudder, adaptive headlight calibration after front-end work, and timing chain tensioner noise on early TSI.',
            'Kodiaq' => 'AdBlue system, third-row AC performance, and parking sensor faults after minor bumps.',
        ),
        'active'        => TRUE,
    ),
    'renault' => array(
        'brand_name'    => 'Renault',
        'slug'          => 'renault',
        'common_models' => array('Kwid', 'Triber', 'Kiger', 'Duster', 'Megane'),
        'intro_copy'    => 'Renault Kwid, Triber, Kiger, and Duster servicing at YMO covers budget-friendly periodic maintenance through to turbo diesel Duster work — honest estimates, trained mechanics, and free pick-up across Pune, Indore, and Nashik.',
        'service_includes' => array(
            'Engine oil and filter change',
            'Brake shoe/pad inspection and adjustment',
            'AC filter cleaning and cooling test',
            'Suspension and steering check on rough-road models',
            'Battery and alternator output test',
            'Doorstep pick-up, workshop service, and return',
        ),
        'common_issues' => array(
            'Kwid / Triber' => 'Clutch cable stretch on manual, AC blower resistor failure, and rear shock absorber wear.',
            'Kiger' => 'Turbo lag on 1.0 TC, infotainment reboots, and ground clearance scrapes on speed breakers.',
            'Duster' => '4×4 vacuum hub service, turbo lag on older dCi, and tailgate strut weakness.',
        ),
        'active'        => TRUE,
    ),
);
