#!/usr/bin/env python3
"""
Scan live WordPress for rev_slider shortcodes and write inventory + optional PHP config.

Usage (repo root):
  python deploy/marketing/scripts/scan_rev_sliders.py
  python deploy/marketing/scripts/scan_rev_sliders.py --write-config
"""
from __future__ import annotations

import argparse
import json
import re
import ssl
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[3]
WP = "https://yourmechaniconline.com"
OUT = ROOT / "deploy" / "marketing" / "generated" / "rev_slider_inventory.json"
SLIDERS_PHP = ROOT / "application" / "config" / "marketing_sliders.php"
REV = re.compile(r"\[rev_slider_vc[^\]]*\]", re.I)
ALIAS = re.compile(r"alias=[\"']([^\"']+)[\"']", re.I)
IMG_RE = re.compile(
    r"https?://(?:www\.)?yourmechaniconline\.com/wp-content/uploads/([^\"'\s>]+\.(?:jpe?g|png|webp))",
    re.I,
)


def fetch(url: str) -> str:
    ctx = ssl.create_default_context()
    req = urllib.request.Request(url, headers={"User-Agent": "YMO-Marketing-Migrator/1.0"})
    with urllib.request.urlopen(req, timeout=60, context=ctx) as resp:
        return resp.read().decode("utf-8", errors="replace")


def fetch_json(url: str) -> list | dict:
    return json.loads(fetch(url))


def fetch_all_pages() -> list[dict]:
    pages: list[dict] = []
    page_num = 1
    while True:
        batch = fetch_json(
            f"{WP}/wp-json/wp/v2/pages?per_page=100&page={page_num}&status=publish&context=edit"
        )
        if not batch:
            break
        pages.extend(batch)
        page_num += 1
    return pages


def path_from_link(link: str) -> str:
    return urlparse(link).path.strip("/").lower()


def php_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def rel_from_url(url: str) -> str | None:
    m = IMG_RE.search(url)
    return m.group(1) if m else None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write-config",
        action="store_true",
        help="Rewrite application/config/marketing_sliders.php from scan results",
    )
    args = parser.parse_args()

    pages = fetch_all_pages()
    by_page: list[dict] = []
    alias_pages: dict[str, list[str]] = {}

    for item in pages:
        content = item.get("content") or {}
        raw = content.get("raw") or content.get("rendered") or ""
        matches = REV.findall(str(raw))
        if not matches:
            continue
        path = path_from_link(item.get("link") or "")
        entry = {
            "wp_id": item.get("id"),
            "path": path,
            "link": item.get("link"),
            "shortcodes": matches,
            "aliases": [],
        }
        for sc in matches:
            m = ALIAS.search(sc)
            if m:
                alias = m.group(1).strip()
                entry["aliases"].append(alias)
                alias_pages.setdefault(alias, []).append(path)
        by_page.append(entry)

    # Homepage rendered HTML often embeds revslider image URLs even when shortcode is gone.
    home_html = fetch(f"{WP}/")
    home_images = sorted({rel_from_url(u) for u in IMG_RE.findall(home_html) if rel_from_url(u)})

    inventory = {
        "pages_with_rev_slider": len(by_page),
        "pages": by_page,
        "alias_pages": alias_pages,
        "homepage_upload_images": home_images,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(inventory, indent=2), encoding="utf-8")

    print(f"Pages with rev_slider shortcode: {len(by_page)}")
    for alias, paths in sorted(alias_pages.items()):
        print(f"  alias {alias!r} -> {paths}")
    print(f"Homepage slider images found: {len(home_images)}")
    print(f"Inventory: {OUT.relative_to(ROOT)}")

    if args.write_config and home_images:
        slides_php = ",\n".join(
            f"            array(\n"
            f"                'src' => {php_str(rel)},\n"
            f"                'alt' => {php_str('Your Mechanic Online')},\n"
            f"            )"
            for rel in home_images
        )
        php = f"""<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/** Auto-generated by scan_rev_sliders.py - edit alt text as needed. */
return array(
    'main' => array(
        'interval_ms' => 6000,
        'slides'      => array(
{slides_php}
        ),
    ),
);
"""
        SLIDERS_PHP.write_text(php, encoding="utf-8")
        print(f"Wrote {SLIDERS_PHP.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
